### ISSUE TITLE
[Login] TypeError: search_ext() argument 3 must be string without null bytes, not str

### ISSUE THREAD

**Issue by mitchins** [linuxserver/docker-ldap-auth#20]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Docker host (Ubuntu 19.10)
Compose snippet:
```
  ldap-auth:
    image: linuxserver/ldap-auth
    deploy:
      placement:
        constraints:
          - node.id == vjy9aa76y05jepfdzqjpvhlu2
    environment:
      - TZ=Australia/Sydney
    ports:
      - 8888:8888
      - 9000:9000
```
Log output:
```
2019-09-06T09:01:21.143640859Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | ----------------------------------------
2019-09-06T09:01:21.144043813Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | Exception happened during processing of request from ('10.0.45.4', 46538)
2019-09-06T09:01:21.144171368Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | ----------------------------------------
2019-09-06T09:01:21.144561378Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | 10.0.45.4 - XXXXXXXXXXXXXXXXXXXXXXXXXX [06/Sep/2019 19:01:11] Error while running search query: search_ext() argument 3 must be string without null bytes, not str, server="ldap://openldap", login="XXXXXXXXXXXXXXXXXXXXXXXXXX"
2019-09-06T09:01:21.144136743Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | Traceback (most recent call last):
2019-09-06T09:01:21.145795547Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | 10.0.45.4 - - [06/Sep/2019 19:01:15] using username/password from cookie nginxauth
2019-09-06T09:01:21.145915076Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | 10.0.45.4 - XXXXXXXXXXXXXXXXXXXXXXXXXX [06/Sep/2019 19:01:16] "GET /auth HTTP/1.0" 401 -
2019-09-06T09:01:21.145969810Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | 10.0.45.4 - - [06/Sep/2019 19:01:20] Trying to dechipher credentials...
2019-09-06T09:01:21.146014493Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | 10.0.45.4 - XXXXXXXXXXXXXXXXXXXXXXXXXX [06/Sep/2019 19:01:21] search_ext() argument 3 must be string without null
bytes, not str
2019-09-06T09:01:21.145863335Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
2019-09-06T09:01:21.146121820Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     self.finish_request(request, client_address)
2019-09-06T09:01:21.146165563Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2019-09-06T09:01:21.146209298Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     self.RequestHandlerClass(request, client_address, self)
2019-09-06T09:01:21.146250895Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
2019-09-06T09:01:21.146292888Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     self.handle()
2019-09-06T09:01:21.146342452Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-09-06T09:01:21.146387250Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     self.handle_one_request()
2019-09-06T09:01:21.146428640Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-09-06T09:01:21.146471170Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     method()
2019-09-06T09:01:21.146512089Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/app/nginx-ldap-auth-daemon.py", line 236, in do_GET
2019-09-06T09:01:21.146553935Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     searchfilter, ['objectclass'], 1)
2019-09-06T09:01:21.146592975Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/site-packages/ldap/ldapobject.py", line 854, in search_s
2019-09-06T09:01:21.146633397Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
2019-09-06T09:01:21.146671111Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/site-packages/ldap/ldapobject.py", line 847, in search_ext_s
2019-09-06T09:01:21.146800193Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
2019-09-06T09:01:21.146860501Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/site-packages/ldap/ldapobject.py", line 843, in search_ext
2019-09-06T09:01:21.146900955Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     timeout,sizelimit,
2019-09-06T09:01:21.147589603Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |   File "/usr/lib/python2.7/site-packages/ldap/ldapobject.py", line 315, in _ldap_call
2019-09-06T09:01:21.147668499Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    |     result = func(*args,**kwargs)
2019-09-06T09:01:21.147712914Z web_ldap-auth.1.oxv2sjm04tgi@cheetah    | TypeError: search_ext() argument 3 must be string without null bytes, not str
```

At a guess, it looks like a combination of:
Uncached or expired cookie (typical ten minute cache was working fine for the last couple days), and switching from safari to Firefox managed to get me through with a fresh login.
At some point its trying to call with a string/bytes mismatch, sounds like a python 2/3 issue, given that python2 is EOL?

**Comment by aptalca** [comment]
@mitchins the image is using python 3 now. Do you still have this issue?

**Comment by aptalca** [comment]
Haven't heard back. Closing.

Feel free to reopen
